/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CreateUserValidationSchema {
  alias?: string;
  email?: string;
  firstName: string;
  home?: {
    address: string;
    city: string;
    country: string;
    zip: string;
  };
  lastName?: string;
  oauth2Identifiers?: {
    opinsys?: string;
  };
  password: string;
  phoneNumber?: string;
  username?: string;
}

export interface LocationSchema {
  address: string;
  city: string;
  country: string;
  zip: string;
}

export interface Oauth2IdentifersValidation {
  opinsys?: string;
}

export interface UpdateUserValidationSchema {
  alias?: string;
  email?: string;
  firstName?: string;
  home?: {
    address: string;
    city: string;
    country: string;
    zip: string;
  };
  id: string;
  lastName?: string;
  oauth2Identifiers?: {
    opinsys?: string;
  };
  password?: string;
  phoneNumber?: string;
  username?: string;
}
