/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface LocationSchema {
  address: string;
  city: string;
  country: string;
  zip: string;
}
